### ISSUE TITLE
INSTALLER WON'T WORK WITH ANOTHER OS ON DRIVE

### ISSUE THREAD

**Issue by dduran1210** [MassOS-Linux/MassOS#23] opened 2022-02-24 23:06 UTC
I ran the installer...got to "select partition"   using fdisk? first line(recommended}....selected partition....selected "write" at the bottom 

and there it sits...no "next" or "continue" buttons....nothing.  tried  dump choice...and it  dumped....lol...into a hole in the ground i guess,

because  we are stuck here.

**Comment by TheSonicMaster** [comment] 2022-02-25 16:39
Hello,

Which installer are you using - the old installer script or the new dialog-based installer on the Live CD? The old script isn't maintained anymore and may be removed in the future, so the Live CD and its installer is recommended instead.

If it's the former, can you provide the output of the script that has been run so far?

If it's the latter, there may be a log file at `/tmp/massos-installerlogXXXXXXXXXX`, where `XXXXXXXXX` is the timestamp. If there is, can you send/attach it? Running `cat /tmp/massos-installerlog*` should give you its output.

Please also provide with the following information:

- Drive type (Hard Drive/SSD/Flash Drive), whether it's an internal or external disk, and the disk's path (`/dev/sda`, `/dev/nvme0n1`, etc.)
- Whether you are booting and installing in Legacy BIOS or UEFI mode (if unsure, you can check by seeing if the directory `/sys/firmware/efi` exists or not).

Also note that the old installer script requires an internet connection to download the rootfs tarball unless you manually download it and pass it as an argument, so check you are connected to the internet.

**Comment by AaronTechnic** [comment] 2022-02-26 08:26
There doesn't seem to be any log.

**Comment by dduran1210** [comment] 2022-02-26 19:23
Try this one.

***@***.***:~$ cat /tmp/massos-installerlog*
mke2fs 1.46.5 (30-Dec-2021)
Discarding device blocks: done
Creating filesystem with 25600000 4k blocks and 6406144 inodes
Filesystem UUID: 73f85f90-8bfa-4b2c-934b-472b863b0cb5
Superblock backups stored on blocks:
32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208,
4096000, 7962624, 11239424, 20480000, 23887872

Allocating group tables: done
Writing inode tables: done
Creating journal (131072 blocks): done
Writing superblocks and filesystem accounting information: done

mount: /dev/sda14 mounted on /tmp/massos-installermnt20220226191242.
mount: /dev/sda15 mounted on
/tmp/massos-installermnt20220226191242/boot/efi.
userdel: massos mail spool (/var/mail/massos) not found
Entering chroot environment in /tmp/massos-installermnt20220226191242...
chroot: failed to run command ‘/usr/sbin/mkinitramfs’: No such file or
directory
Exiting chroot environment...
Chroot exited with unsuccessful exit code 127.
***@***.***:~$

**Comment by TheSonicMaster** [comment] 2022-02-27 00:22
So the problem is occuring at generating the initramfs, and not being able to locate the `mkinitramfs` utility. Previously you mentioned the problem being hanging at the disk setup stage. Are these issues related - is this the same issue or a different issue? If they are different, was the previous issue fixed?

The initramfs generation stage is not run until after the system is installed and the basic setup is done (the full order is disk setup --> installation (extracting squashfs) --> locale/keymap --> timezone --> root password --> user setup --> initramfs --> bootloader), so did it somehow skip all the way from disk setup to initramfs generation?

Additionally, what version of MassOS are you installing?

**Comment by dduran1210** [comment] 2022-02-27 06:57
massos-2022.02.2-x86_64.iso

it is the same issue.   i go thru the installation steps:   1.
install...2.  select  manual partition....location,  name.... then it
copies the files...then i select the partition, and make the efi partition,
and  then it wants to create a swap partition....and I ALREADY HAVE A 4GB
SWAP PARTITION INSTALLED.....so i select  NO....AND get the error message
that i sent you.
I started all over again and at the "swap" request...i said YES....and
selected the swap partition that is on the hard drive  sda2....AND GET THE
ERROR MESSAGE AGAIN...SAME ONE.

**Comment by TheSonicMaster** [comment] 2022-02-27 12:46
If you are doing option 2 (Install to existing partition) and already have a swap partition, you don't need to select No at the swap choice - you can select Yes and if you already have a swap partition, it will let you select your existing one and it won't reformat it. The same goes for the EFI system partition, if you already have one used by another operating system, it can share it and you don't need to create another.

I've noticed how the message could be misleading as it implies it's going to create another swap partition when it's actually just going to use an existing one you have. This wording has now been fixed in https://github.com/MassOS-Linux/livecd-installer/commit/461074f2c7979092abe211cd17bebaf63f36d617 - the next version of MassOS will include this rewording.

Was the swap partition already swapped on when you got to the installer stage? If so, you might have to manually swap it off with the `swapoff` command - the installer will automatically swap it on when it needs to. Maybe something went wrong due to the Swap partition already being swapped on when running the installer - I am unsure. In either case, it might be best to reboot the live CD to restart the installer rather than just restarting the installer directly.

I tried to replicate your issue as closely as I could by installing Ubuntu in UEFI mode in a virtual machine with a swap partition, then booting a MassOS 2022.02.2 live CD and installing MassOS in a dual-boot on the same virtual machine. I had already set up my partitions manually using the Gparted application before running the installer. In the installer, I selected option 2 --> the partition to install MassOS on --> filesystem ext4 --> selected the EFI partition which was the same one also used by Ubuntu --> Selected Yes at the swap choice --> Selected the swap partition which Ubuntu also used --> Selected Yes at the confirmation prompt --> Waited for the installation to complete --> Went through the basic setup --> Successfully finished the installation. I was unable to replicate your issue.

**Comment by dduran1210** [comment] 2022-02-27 17:16
ok,  so how do i get the corrected livecd to download?

**Comment by dduran1210** [comment] 2022-02-27 20:48
Hi again....

OK, OK, OK......LOL.

i FOLLOWED YOUR LAST EMAIL STEPS AND  I GOT IT INSTALLED.

I just don't know what i was doing wrong...except on the swap  create,  i
was worried about how it wanted to format it and I
assumed that it would screw up my other os's that were using it. But i
realized it was no big deal...so i went ahead and accepted the format
and it installed perfectly.

anyway,  i THANK YOU very much for your patience.

I really like your program.

Dave

**Comment by TheSonicMaster** [comment] 2022-02-27 23:56
You're welcome. I agree the message about adding a swap partition was misleading; it has now been reworded and this will be incorporated into the next version of MassOS. Glad it's now working for you.

**Closed by TheSonicMaster** 2022-02-27 23:56 UTC
Labels: more information needed, installation, livecd

**Comment by dduran1210** [comment] 2022-02-28 00:18
Awesome, thanks!   but now I got another BIG problem on here.   the
xfce4-terminal  DOES NOT WORK !

"apt" is not found error message   when i type sudo apt
install......anything

dpkg  is also not found error message.

can't install anything !

how do we fix this ?

**Comment by dduran1210** [comment] 2022-02-28 18:43
nevermind,  I will just uninstall the OS and re-install it .
