### ISSUE TITLE
[Bug]: Firefox is very slow to start

### ISSUE THREAD

**Issue by mfat** [MassOS-Linux/MassOS#29] opened 2022-04-15 19:16 UTC
### Checklist

- [X] I have searched for [other issues](https://www.github.com/MassOS-Linux/MassOS/issues), and can confirm my issue has not already been reported.
- [X] If this is an issue with a specific program, I have checked the upstream project's issue tracker and determined that it is an issue with MassOS itself.

### MassOS version

2022.04

### Kernel version

Linux 5.17.1-massos #1 SMP PREEMPT Tue Mar 29 06:14:09 UTC 2022 x86_64

### Subject

- [X] Issue at runtime of MassOS.
- [ ] Issue with the MassOS Live CD.
- [ ] Issue with installing MassOS.
- [ ] Issue with the MassOS documentation.
- [ ] Issue compiling MassOS from source.

### Expected Behavior

I expect Firefox to open quickly as the whole system is very snappy

### Actual Behavior

Firefox takes a long time to start. Unusually long. 

### Steps to reproduce

Open Browser

**Comment by TheSonicMaster** [comment] 2022-04-15 19:41
Thanks for pointing this out. I can confirm this is a bug affecting MassOS version 2022.04 and later. I have been looking into it for a while now, and will keep this issue's comments updated as necessary.

**Comment by TheSonicMaster** [comment] 2022-04-16 17:32
It looks like this issue started with Firefox 98. Firefox 97 and previous versions, including Firefox ESR 91, are not affected. Until this gets fixed, I assume for now as a workaround you could use one of these versions older versions (all releases can be downloaded from https://archive.mozilla.org/pub/firefox/releases/), or use another browser. It's not ideal, but hopefully this issue will be fixed soon.

**Comment by TheSonicMaster** [comment] 2022-06-25 14:35
This should now be fixed in https://github.com/MassOS-Linux/MassOS/commit/bb9bd5f7d2deb06c3a8ddb4b71cec4b543d01562.

Providing it doesn't cause subsequent regressions, this fix will be included in the next release of MassOS, which will be 2022.07. However you can apply the fix immediately by doing the following:

1. Open a terminal (Control+Alt+T).
2. Switch to root by running `sudo su` or `pkexec su`. Type your user password if prompted.
3. Copy and paste this (if you get a warning about a dangerous paste, ignore it and continue), then press enter:
```
cat > /etc/xdg/autostart/xdg-desktop-portal-gtk.desktop << "END"
[Desktop Entry]
Type=Application
Name=Portal service (GTK/GNOME implementation)
Exec=/bin/bash -c "dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY; systemctl start --user xdg-desktop-portal-gtk.service"
END
```
4. Reboot or logout and log back into your desktop. The issue should be fixed.

**Comment by TheSonicMaster** [comment] 2022-07-02 11:52
The fix is now incorporated in the latest release (2022.07), https://github.com/MassOS-Linux/MassOS/releases/tag/v2022.07.

**Closed by TheSonicMaster** 2022-07-02 11:52 UTC
Labels: bug, runtime
